spring:
  profiles:
    active: kubernetes
  cloud:
    kubernetes:
      discovery:
        discovery-server-url: http://spring-cloud-kubernetes-discoveryserver:8761
  application:
    name: client-service

server:
  port: 7070

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true